In [1]:
# AI기반 네트워크 위협탐지 미니 챌린지

import pandas as pd
import numpy as np

# 데이터 불러오기
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
answer = pd.read_csv('answer.csv')

train.shape, test.shape, answer.shape

((19735, 23), (1631, 21), (1631, 2))

In [2]:
# 데이터 시각화

# import matplotlib.pyplot as plt

# 데이터 분포 확인
# 정상과 악성의 분포 확인

# plt.figure(figsize=(5, 5))
# plt.title('class distribution')
# plt.bar(train['class'].unique(), train['class'].value_counts(), width=0.3, color=['skyblue', 'pink'])
# plt.xticks(train['class'].unique())
# plt.xlabel('class (0: normal, 1: malicious)')
# plt.ylabel('count')
# plt.show()

# print(train['class'].value_counts())

In [3]:
# class 별 데이터 분포 확인
# class 별 id.orig_p의 분포 확인

# plt.figure(figsize=(5, 5))
# plt.title('id.orig_p distribution')
# plt.hist(train[train['class'] == 0]['id.orig_p'], color='skyblue', label='normal', alpha=0.5)
# plt.hist(train[train['class'] == 1]['id.orig_p'], color='pink', label='malicious', alpha=0.5)
# plt.legend()
# plt.xlabel('id.orig_p')
# plt.ylabel('count')
# plt.show()

In [4]:
# class 별 id.resp_p의 분포 확인

# plt.figure(figsize=(5, 5))
# plt.title('id.resp_p distribution')
# plt.hist(train[train['class'] == 0]['id.resp_p'], color='skyblue', label='normal', alpha=0.5)
# plt.hist(train[train['class'] == 1]['id.resp_p'], color='pink', label='malicious', alpha=0.5)
# plt.legend()
# plt.xlabel('id.resp_p')
# plt.ylabel('count')

In [5]:
# class 별 proto 분포 시각화 with pandas

# train.groupby('class')['proto'].value_counts().plot(kind='bar', figsize=(5, 5), color=['skyblue', 'pink', 'lightgreen'], alpha=0.5, rot=0)

In [6]:
# class 별 service 분포 시각화 with pandas

# train.groupby('class')['service'].value_counts().plot(kind='bar', figsize=(5, 5), color=['skyblue', 'pink', 'lightgreen'], alpha=0.5, rot=45)

In [7]:
# duration 분포 확인

# len(train[train['duration'] == '-'])

In [8]:
# duration이 '-'인 데이터의 duration을 0으로 변경

# train.loc[train['duration'] == '-', 'duration'] = 0
# len(train[train['duration'] == '-'])

In [9]:
# duration 데이터 타입 변경 후 시각화

# train['duration'] = train['duration'].astype('float64')

# plt.figure(figsize=(5, 5))
# plt.title('duration distribution')
# plt.hist(train[train['class'] == 0]['duration'], color='skyblue', label='normal', alpha=0.5)
# plt.hist(train[train['class'] == 1]['duration'], color='pink', label='malicious', alpha=0.5)
# plt.legend()
# plt.xlabel('duration')
# plt.ylabel('count')
# plt.show()

In [10]:
# resp_ip_bytes 분포 시각화 with seaborn

# import seaborn as sns

# plt.figure(figsize=(5, 5))
# plt.title('resp_ip_bytes distribution')
# sns.kdeplot(train[train['class'] == 0]['resp_ip_bytes'], color='skyblue', label='normal')
# sns.kdeplot(train[train['class'] == 1]['resp_ip_bytes'], color='pink', label='malicious')
# plt.legend()
# plt.xlabel('resp_ip_bytes')
# plt.ylabel('count')
# plt.show()

In [11]:
# 데이터 모양 확인

train

,Unnamed: 0,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,...,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,class
0,0,1632859201.94749,CPNl6k3JbVOG4tz1Zd,192.168.87.131,60615.0,192.168.87.2,53.0,udp,dns,0.270559,...,T,T,0.0,Dd,1.0,62.0,1.0,137.0,(empty),0.0
1,1,1632859159.2100391,COUSXg4wGYe6luWFG8,fe80::20c:29ff:fe9f:ebb,133.0,ff02::2,134.0,icmp,-,-,...,F,F,0.0,-,1.0,56.0,0.0,0.0,(empty),0.0
2,2,1632859214.3695712,CuEEhk3Wt5ChCk2U6f,192.168.87.131,55924.0,192.168.87.2,53.0,udp,dns,0.023672,...,T,T,0.0,Dd,1.0,70.0,1.0,177.0,(empty),0.0
3,3,1632859214.400497,CEEAX035N9QYuH3Xq5,192.168.87.131,54692.0,192.168.87.2,53.0,udp,dns,0.018691,...,T,T,0.0,Dd,1.0,71.0,1.0,178.0,(empty),0.0
4,4,1632859214.424631,Cml68B12Tm1BNYtiBl,192.168.87.131,37227.0,192.168.87.2,53.0,udp,dns,0.002733,...,T,T,0.0,Dd,1.0,73.0,1.0,128.0,(empty),0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,3525,1632937604.975284,Ck9Vxk3npjUeqwmjC6,20.20.20.100,65216.0,203.217.236.19,443.0,tcp,ssl,0.012203,...,T,F,3754.0,ShADacFr,6.0,776.0,5.0,204.0,(empty),0.0
19731,3526,1632937553.091704,CURubA6OnYIs9UFQ1,192.168.87.130,54735.0,216.58.220.110,443.0,udp,-,0.204099,...,T,F,0.0,Dd,9.0,3875.0,10.0,4356.0,(empty),0.0
19732,3527,1632937553.091831,CrmjFs1glyZyU4aQwg,20.20.20.100,54735.0,216.58.220.110,443.0,udp,-,0.204107,...,T,F,0.0,Dd,9.0,3875.0,10.0,4356.0,(empty),0.0
19733,3528,1632937540.984622,C0yAyZ1EYy1KC50ovl,192.168.87.130,55672.0,8.8.4.4,443.0,udp,-,18.059633,...,T,F,0.0,Dd,22.0,3821.0,28.0,8203.0,(empty),0.0
19734,3529,1632937540.9848368,C6wugh1Lw2m6sgXwqi,20.20.20.100,55672.0,8.8.4.4,443.0,udp,-,18.059590,...,T,F,0.0,Dd,22.0,3821.0,28.0,8203.0,(empty),0.0

In [12]:
# 데이터 전처리

# 1. 학습 미사용 데이터 제거 (Unnamed: 0, ts, uid, id.orig_h, id.resp_h, tunnel_parents)

train.drop(['Unnamed: 0', 'ts', 'uid', 'id.orig_h', 'id.resp_h', 'tunnel_parents'], axis=1, inplace=True)
train

,id.orig_p,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,class
0,60615.0,53.0,udp,dns,0.270559,34,109,SF,T,T,0.0,Dd,1.0,62.0,1.0,137.0,0.0
1,133.0,134.0,icmp,-,-,-,-,OTH,F,F,0.0,-,1.0,56.0,0.0,0.0,0.0
2,55924.0,53.0,udp,dns,0.023672,42,149,SF,T,T,0.0,Dd,1.0,70.0,1.0,177.0,0.0
3,54692.0,53.0,udp,dns,0.018691,43,150,SF,T,T,0.0,Dd,1.0,71.0,1.0,178.0,0.0
4,37227.0,53.0,udp,dns,0.002733,45,100,SF,T,T,0.0,Dd,1.0,73.0,1.0,128.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,65216.0,443.0,tcp,ssl,0.012203,524,3754,RSTR,T,F,3754.0,ShADacFr,6.0,776.0,5.0,204.0,0.0
19731,54735.0,443.0,udp,-,0.204099,3623,4076,SF,T,F,0.0,Dd,9.0,3875.0,10.0,4356.0,0.0
19732,54735.0,443.0,udp,-,0.204107,3623,4076,SF,T,F,0.0,Dd,9.0,3875.0,10.0,4356.0,0.0
19733,55672.0,443.0,udp,-,18.059633,3205,7419,SF,T,F,0.0,Dd,22.0,3821.0,28.0,8203.0,0.0
19734,55672.0,443.0,udp,-,18.059590,3205,7419,SF,T,F,0.0,Dd,22.0,3821.0,28.0,8203.0,0.0

In [13]:
# 2. 결측치 확인

train[train.isnull().any(axis=1)]

,id.orig_p,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,class
12352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
16204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [14]:
# 결측치 제거 및 라벨 분리

train.dropna(inplace=True)
train_label = train['class']
train.drop('class', axis=1, inplace=True)

In [15]:
# 3. id.orig_p, id.resp_p 전처리, 포트 정보이므로 int형으로 변경

train['id.orig_p'] = train['id.orig_p'].astype('int64')
train['id.resp_p'] = train['id.resp_p'].astype('int64')
train

,id.orig_p,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes
0,60615,53,udp,dns,0.270559,34,109,SF,T,T,0.0,Dd,1.0,62.0,1.0,137.0
1,133,134,icmp,-,-,-,-,OTH,F,F,0.0,-,1.0,56.0,0.0,0.0
2,55924,53,udp,dns,0.023672,42,149,SF,T,T,0.0,Dd,1.0,70.0,1.0,177.0
3,54692,53,udp,dns,0.018691,43,150,SF,T,T,0.0,Dd,1.0,71.0,1.0,178.0
4,37227,53,udp,dns,0.002733,45,100,SF,T,T,0.0,Dd,1.0,73.0,1.0,128.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,65216,443,tcp,ssl,0.012203,524,3754,RSTR,T,F,3754.0,ShADacFr,6.0,776.0,5.0,204.0
19731,54735,443,udp,-,0.204099,3623,4076,SF,T,F,0.0,Dd,9.0,3875.0,10.0,4356.0
19732,54735,443,udp,-,0.204107,3623,4076,SF,T,F,0.0,Dd,9.0,3875.0,10.0,4356.0
19733,55672,443,udp,-,18.059633,3205,7419,SF,T,F,0.0,Dd,22.0,3821.0,28.0,8203.0
19734,55672,443,udp,-,18.059590,3205,7419,SF,T,F,0.0,Dd,22.0,3821.0,28.0,8203.0

In [16]:
# 4. proto 전처리 - one-hot encoding

from sklearn.preprocessing import OneHotEncoder

proto_ohe = OneHotEncoder(sparse=False)
proto_ohe.fit(train[['proto']])
proto_ohe_df = pd.DataFrame(proto_ohe.transform(train[['proto']]), columns=proto_ohe.categories_[0], index=train.index)
train = pd.concat([train, proto_ohe_df], axis=1)
train.drop(['proto'], axis=1, inplace=True)
train

c:\Users\Gloomy\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,id.orig_p,id.resp_p,service,duration,orig_bytes,resp_bytes,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,icmp,tcp,udp
0,60615,53,dns,0.270559,34,109,SF,T,T,0.0,Dd,1.0,62.0,1.0,137.0,0.0,0.0,1.0
1,133,134,-,-,-,-,OTH,F,F,0.0,-,1.0,56.0,0.0,0.0,1.0,0.0,0.0
2,55924,53,dns,0.023672,42,149,SF,T,T,0.0,Dd,1.0,70.0,1.0,177.0,0.0,0.0,1.0
3,54692,53,dns,0.018691,43,150,SF,T,T,0.0,Dd,1.0,71.0,1.0,178.0,0.0,0.0,1.0
4,37227,53,dns,0.002733,45,100,SF,T,T,0.0,Dd,1.0,73.0,1.0,128.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,65216,443,ssl,0.012203,524,3754,RSTR,T,F,3754.0,ShADacFr,6.0,776.0,5.0,204.0,0.0,1.0,0.0
19731,54735,443,-,0.204099,3623,4076,SF,T,F,0.0,Dd,9.0,3875.0,10.0,4356.0,0.0,0.0,1.0
19732,54735,443,-,0.204107,3623,4076,SF,T,F,0.0,Dd,9.0,3875.0,10.0,4356.0,0.0,0.0,1.0
19733,55672,443,-,18.059633,3205,7419,SF,T,F,0.0,Dd,22.0,3821.0,28.0,8203.0,0.0,0.0,1.0
19734,55672,443,-,18.059590,3205,7419,SF,T,F,0.0,Dd,22.0,3821.0,28.0,8203.0,0.0,0.0,1.0

In [17]:
# 5. service 전처리 - one-hot encoding

service_ohe = OneHotEncoder(sparse=False)
service_ohe.fit(train[['service']])
service_ohe_df = pd.DataFrame(service_ohe.transform(train[['service']]), columns=['service_-', 'dhcp', 'dns', 'dtls', 'http', 'ssl'], index=train.index)
train = pd.concat([train, service_ohe_df], axis=1)
train.drop(['service'], axis=1, inplace=True)
train

c:\Users\Gloomy\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,conn_state,local_orig,local_resp,missed_bytes,history,...,resp_ip_bytes,icmp,tcp,udp,service_-,dhcp,dns,dtls,http,ssl
0,60615,53,0.270559,34,109,SF,T,T,0.0,Dd,...,137.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,133,134,-,-,-,OTH,F,F,0.0,-,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,55924,53,0.023672,42,149,SF,T,T,0.0,Dd,...,177.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,54692,53,0.018691,43,150,SF,T,T,0.0,Dd,...,178.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,37227,53,0.002733,45,100,SF,T,T,0.0,Dd,...,128.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,65216,443,0.012203,524,3754,RSTR,T,F,3754.0,ShADacFr,...,204.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19731,54735,443,0.204099,3623,4076,SF,T,F,0.0,Dd,...,4356.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
19732,54735,443,0.204107,3623,4076,SF,T,F,0.0,Dd,...,4356.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
19733,55672,443,18.059633,3205,7419,SF,T,F,0.0,Dd,...,8203.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
19734,55672,443,18.059590,3205,7419,SF,T,F,0.0,Dd,...,8203.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0

In [18]:
# 6. duration 전처리 - '-' 데이터 0으로 변경 후 float형으로 변경, 스케일링

from sklearn.preprocessing import StandardScaler

train['duration'] = train['duration'].str.replace('-', '0')
train['duration'] = train['duration'].astype('float64')
scaler = StandardScaler()
train['duration'] = scaler.fit_transform(train[['duration']])
train

,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,conn_state,local_orig,local_resp,missed_bytes,history,...,resp_ip_bytes,icmp,tcp,udp,service_-,dhcp,dns,dtls,http,ssl
0,60615,53,-0.455602,34,109,SF,T,T,0.0,Dd,...,137.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,133,134,-0.457459,-,-,OTH,F,F,0.0,-,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,55924,53,-0.457297,42,149,SF,T,T,0.0,Dd,...,177.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,54692,53,-0.457331,43,150,SF,T,T,0.0,Dd,...,178.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,37227,53,-0.457440,45,100,SF,T,T,0.0,Dd,...,128.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,65216,443,-0.457375,524,3754,RSTR,T,F,3754.0,ShADacFr,...,204.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19731,54735,443,-0.456058,3623,4076,SF,T,F,0.0,Dd,...,4356.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
19732,54735,443,-0.456058,3623,4076,SF,T,F,0.0,Dd,...,4356.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
19733,55672,443,-0.333491,3205,7419,SF,T,F,0.0,Dd,...,8203.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
19734,55672,443,-0.333491,3205,7419,SF,T,F,0.0,Dd,...,8203.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0

In [19]:
# 7. orig_bytes, resp_bytes 전처리 - '-' 데이터 0으로 변경 후 float형으로 변경, 스케일링

train['orig_bytes'] = train['orig_bytes'].str.replace('-', '0')
train['orig_bytes'] = train['orig_bytes'].astype('float64')
scaler = StandardScaler()
train['orig_bytes'] = scaler.fit_transform(train[['orig_bytes']])

train['resp_bytes'] = train['resp_bytes'].str.replace('-', '0')
train['resp_bytes'] = train['resp_bytes'].astype('float64')
scaler = StandardScaler()
train['resp_bytes'] = scaler.fit_transform(train[['resp_bytes']])

train

,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,conn_state,local_orig,local_resp,missed_bytes,history,...,resp_ip_bytes,icmp,tcp,udp,service_-,dhcp,dns,dtls,http,ssl
0,60615,53,-0.455602,-0.105905,-0.028721,SF,T,T,0.0,Dd,...,137.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,133,134,-0.457459,-0.107722,-0.028750,OTH,F,F,0.0,-,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,55924,53,-0.457297,-0.105478,-0.028711,SF,T,T,0.0,Dd,...,177.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,54692,53,-0.457331,-0.105424,-0.028710,SF,T,T,0.0,Dd,...,178.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,37227,53,-0.457440,-0.105317,-0.028723,SF,T,T,0.0,Dd,...,128.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,65216,443,-0.457375,-0.079714,-0.027769,RSTR,T,F,3754.0,ShADacFr,...,204.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19731,54735,443,-0.456058,0.085933,-0.027684,SF,T,F,0.0,Dd,...,4356.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
19732,54735,443,-0.456058,0.085933,-0.027684,SF,T,F,0.0,Dd,...,4356.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
19733,55672,443,-0.333491,0.063590,-0.026811,SF,T,F,0.0,Dd,...,8203.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
19734,55672,443,-0.333491,0.063590,-0.026811,SF,T,F,0.0,Dd,...,8203.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0

In [20]:
# conn_state 전처리 - one-hot encoding

conn_state_ohe = OneHotEncoder(sparse=False)
conn_state_ohe.fit(train[['conn_state']])
conn_state_ohe_df = pd.DataFrame(conn_state_ohe.transform(train[['conn_state']]), columns=conn_state_ohe.categories_[0], index=train.index)
train = pd.concat([train, conn_state_ohe_df], axis=1)
train.drop(['conn_state'], axis=1, inplace=True)
train

c:\Users\Gloomy\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,local_orig,local_resp,missed_bytes,history,orig_pkts,...,RSTO,RSTR,RSTRH,S0,S1,S2,S3,SF,SH,SHR
0,60615,53,-0.455602,-0.105905,-0.028721,T,T,0.0,Dd,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,133,134,-0.457459,-0.107722,-0.028750,F,F,0.0,-,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,55924,53,-0.457297,-0.105478,-0.028711,T,T,0.0,Dd,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,54692,53,-0.457331,-0.105424,-0.028710,T,T,0.0,Dd,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,37227,53,-0.457440,-0.105317,-0.028723,T,T,0.0,Dd,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,65216,443,-0.457375,-0.079714,-0.027769,T,F,3754.0,ShADacFr,6.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19731,54735,443,-0.456058,0.085933,-0.027684,T,F,0.0,Dd,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19732,54735,443,-0.456058,0.085933,-0.027684,T,F,0.0,Dd,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19733,55672,443,-0.333491,0.063590,-0.026811,T,F,0.0,Dd,22.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19734,55672,443,-0.333491,0.063590,-0.026811,T,F,0.0,Dd,22.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [21]:
# local_orig, local_resp 전처리 - one-hot encoding

local_orig_ohe = OneHotEncoder(sparse=False)
local_orig_ohe.fit(train[['local_orig']])
local_orig_ohe_df = pd.DataFrame(local_orig_ohe.transform(train[['local_orig']]), columns=['local_orig_F', 'local_orig_T'], index=train.index)
train = pd.concat([train, local_orig_ohe_df], axis=1)
train.drop(['local_orig'], axis=1, inplace=True)

local_resp_ohe = OneHotEncoder(sparse=False)
local_resp_ohe.fit(train[['local_resp']])
local_resp_ohe_df = pd.DataFrame(local_resp_ohe.transform(train[['local_resp']]), columns=['local_resp_F', 'local_resp_T'], index=train.index)
train = pd.concat([train, local_resp_ohe_df], axis=1)
train.drop(['local_resp'], axis=1, inplace=True)

train

c:\Users\Gloomy\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
c:\Users\Gloomy\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,...,S1,S2,S3,SF,SH,SHR,local_orig_F,local_orig_T,local_resp_F,local_resp_T
0,60615,53,-0.455602,-0.105905,-0.028721,0.0,Dd,1.0,62.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
1,133,134,-0.457459,-0.107722,-0.028750,0.0,-,1.0,56.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,55924,53,-0.457297,-0.105478,-0.028711,0.0,Dd,1.0,70.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
3,54692,53,-0.457331,-0.105424,-0.028710,0.0,Dd,1.0,71.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
4,37227,53,-0.457440,-0.105317,-0.028723,0.0,Dd,1.0,73.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,65216,443,-0.457375,-0.079714,-0.027769,3754.0,ShADacFr,6.0,776.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
19731,54735,443,-0.456058,0.085933,-0.027684,0.0,Dd,9.0,3875.0,10.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
19732,54735,443,-0.456058,0.085933,-0.027684,0.0,Dd,9.0,3875.0,10.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
19733,55672,443,-0.333491,0.063590,-0.026811,0.0,Dd,22.0,3821.0,28.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
19734,55672,443,-0.333491,0.063590,-0.026811,0.0,Dd,22.0,3821.0,28.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0

In [22]:
# missed_bytes 전처리 - 스케일링

scaler = StandardScaler()
train['missed_bytes'] = scaler.fit_transform(train[['missed_bytes']])
train

,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,...,S1,S2,S3,SF,SH,SHR,local_orig_F,local_orig_T,local_resp_F,local_resp_T
0,60615,53,-0.455602,-0.105905,-0.028721,-0.052860,Dd,1.0,62.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
1,133,134,-0.457459,-0.107722,-0.028750,-0.052860,-,1.0,56.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,55924,53,-0.457297,-0.105478,-0.028711,-0.052860,Dd,1.0,70.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
3,54692,53,-0.457331,-0.105424,-0.028710,-0.052860,Dd,1.0,71.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
4,37227,53,-0.457440,-0.105317,-0.028723,-0.052860,Dd,1.0,73.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,65216,443,-0.457375,-0.079714,-0.027769,-0.049589,ShADacFr,6.0,776.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
19731,54735,443,-0.456058,0.085933,-0.027684,-0.052860,Dd,9.0,3875.0,10.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
19732,54735,443,-0.456058,0.085933,-0.027684,-0.052860,Dd,9.0,3875.0,10.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
19733,55672,443,-0.333491,0.063590,-0.026811,-0.052860,Dd,22.0,3821.0,28.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
19734,55672,443,-0.333491,0.063590,-0.026811,-0.052860,Dd,22.0,3821.0,28.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0

In [23]:
# history 전처리 - one-hot encoding

history_ohe = OneHotEncoder(sparse=False)
history_ohe.fit(train[['history']])
history_ohe_df = pd.DataFrame(history_ohe.transform(train[['history']]), columns=history_ohe.categories_[0], index=train.index)
train = pd.concat([train, history_ohe_df], axis=1)
train.drop(['history'], axis=1, inplace=True)
train

c:\Users\Gloomy\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,...,ShfqR,^d,^dCa,^dCaf,^hCacdfA,^hCacdfR,^hCadc,^hCadcfA,^hCadfA,^r
0,60615,53,-0.455602,-0.105905,-0.028721,-0.052860,1.0,62.0,1.0,137.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,133,134,-0.457459,-0.107722,-0.028750,-0.052860,1.0,56.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,55924,53,-0.457297,-0.105478,-0.028711,-0.052860,1.0,70.0,1.0,177.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,54692,53,-0.457331,-0.105424,-0.028710,-0.052860,1.0,71.0,1.0,178.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,37227,53,-0.457440,-0.105317,-0.028723,-0.052860,1.0,73.0,1.0,128.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,65216,443,-0.457375,-0.079714,-0.027769,-0.049589,6.0,776.0,5.0,204.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19731,54735,443,-0.456058,0.085933,-0.027684,-0.052860,9.0,3875.0,10.0,4356.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19732,54735,443,-0.456058,0.085933,-0.027684,-0.052860,9.0,3875.0,10.0,4356.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19733,55672,443,-0.333491,0.063590,-0.026811,-0.052860,22.0,3821.0,28.0,8203.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19734,55672,443,-0.333491,0.063590,-0.026811,-0.052860,22.0,3821.0,28.0,8203.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
# orig_pkts, orig_ip_bytes, resp_pkts, resp_ip_bytes 전처리 - 스케일링

scaler = StandardScaler()
train['orig_pkts'] = scaler.fit_transform(train[['orig_pkts']])
train['orig_ip_bytes'] = scaler.fit_transform(train[['orig_ip_bytes']])
train['resp_pkts'] = scaler.fit_transform(train[['resp_pkts']])
train['resp_ip_bytes'] = scaler.fit_transform(train[['resp_ip_bytes']])
train

,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,...,ShfqR,^d,^dCa,^dCaf,^hCacdfA,^hCacdfR,^hCadc,^hCadcfA,^hCadfA,^r
0,60615,53,-0.455602,-0.105905,-0.028721,-0.052860,-0.059970,-0.092511,-0.018091,-0.026545,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,133,134,-0.457459,-0.107722,-0.028750,-0.052860,-0.059970,-0.092737,-0.018456,-0.026580,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,55924,53,-0.457297,-0.105478,-0.028711,-0.052860,-0.059970,-0.092210,-0.018091,-0.026534,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,54692,53,-0.457331,-0.105424,-0.028710,-0.052860,-0.059970,-0.092172,-0.018091,-0.026534,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,37227,53,-0.457440,-0.105317,-0.028723,-0.052860,-0.059970,-0.092097,-0.018091,-0.026547,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,65216,443,-0.457375,-0.079714,-0.027769,-0.049589,-0.044527,-0.065623,-0.016630,-0.026527,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19731,54735,443,-0.456058,0.085933,-0.027684,-0.052860,-0.035261,0.051077,-0.014804,-0.025459,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19732,54735,443,-0.456058,0.085933,-0.027684,-0.052860,-0.035261,0.051077,-0.014804,-0.025459,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19733,55672,443,-0.333491,0.063590,-0.026811,-0.052860,0.004889,0.049043,-0.008229,-0.024469,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19734,55672,443,-0.333491,0.063590,-0.026811,-0.052860,0.004889,0.049043,-0.008229,-0.024469,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
# train 데이터 전처리 완료, test 데이터 전처리

# 1. 학습 미사용 데이터 제거 (Unnamed: 0, ts, uid, id.orig_h, id.resp_h, tunnel_parents) 및 라벨 분리

test.drop(['Unnamed: 0', 'ts', 'uid', 'tunnel_parents'], axis=1, inplace=True)
test_label = test['class']
test.drop('class', axis=1, inplace=True)

In [26]:
# 2. 결측치 확인

test.isnull().sum()

id.orig_p        0
id.resp_p        0
proto            0
service          0
duration         0
orig_bytes       0
resp_bytes       0
conn_state       0
local_orig       0
local_resp       0
missed_bytes     0
history          0
orig_pkts        0
orig_ip_bytes    0
resp_pkts        0
resp_ip_bytes    0
dtype: int64

In [27]:
# 3. id.orig_p, id.resp_p 전처리, 포트 정보이므로 int형으로 변경

test['id.orig_p'] = test['id.orig_p'].astype('int64')
test['id.resp_p'] = test['id.resp_p'].astype('int64')
test

,id.orig_p,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes
0,60389,445,tcp,-,-,-,-,SH,T,T,0,F,1,52,0,0
1,52090,443,tcp,-,0.028626,0,0,SF,T,F,0,FafA,2,80,2,80
2,59672,443,tcp,-,0.028758,0,0,SF,T,F,0,FafA,2,80,2,80
3,57505,443,tcp,-,0.028336,0,0,SF,T,F,0,FafA,2,80,2,80
4,52090,443,tcp,-,0.028459,0,0,SF,T,F,0,FafA,2,80,2,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1626,137,137,udp,dns,17.497227,900,0,S0,T,T,0,D,18,1404,0,0
1627,138,138,udp,-,-,-,-,S0,T,T,0,D,1,229,0,0
1628,33561,445,tcp,-,-,-,-,SH,T,T,0,F,1,52,0,0
1629,50410,443,tcp,-,20.098036,1647,1064,SF,T,F,0,ShADadfF,13,2179,15,1668
1630,50410,443,tcp,-,20.098292,1647,1064,SF,T,F,0,ShADadfF,13,2179,15,1668

In [28]:
# 4. proto 전처리 - one-hot encoding

proto_ohe_df = pd.DataFrame(proto_ohe.transform(test[['proto']]), columns=proto_ohe.categories_[0], index=test.index)
test = pd.concat([test, proto_ohe_df], axis=1)
test.drop(['proto'], axis=1, inplace=True)
test

,id.orig_p,id.resp_p,service,duration,orig_bytes,resp_bytes,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,icmp,tcp,udp
0,60389,445,-,-,-,-,SH,T,T,0,F,1,52,0,0,0.0,1.0,0.0
1,52090,443,-,0.028626,0,0,SF,T,F,0,FafA,2,80,2,80,0.0,1.0,0.0
2,59672,443,-,0.028758,0,0,SF,T,F,0,FafA,2,80,2,80,0.0,1.0,0.0
3,57505,443,-,0.028336,0,0,SF,T,F,0,FafA,2,80,2,80,0.0,1.0,0.0
4,52090,443,-,0.028459,0,0,SF,T,F,0,FafA,2,80,2,80,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1626,137,137,dns,17.497227,900,0,S0,T,T,0,D,18,1404,0,0,0.0,0.0,1.0
1627,138,138,-,-,-,-,S0,T,T,0,D,1,229,0,0,0.0,0.0,1.0
1628,33561,445,-,-,-,-,SH,T,T,0,F,1,52,0,0,0.0,1.0,0.0
1629,50410,443,-,20.098036,1647,1064,SF,T,F,0,ShADadfF,13,2179,15,1668,0.0,1.0,0.0
1630,50410,443,-,20.098292,1647,1064,SF,T,F,0,ShADadfF,13,2179,15,1668,0.0,1.0,0.0

In [29]:
# 5. service 전처리 - one-hot encoding

service_ohe_df = pd.DataFrame(service_ohe.transform(test[['service']]), columns=['service_-', 'dhcp', 'dns', 'dtls', 'http', 'ssl'], index=test.index)
test = pd.concat([test, service_ohe_df], axis=1)
test.drop(['service'], axis=1, inplace=True)
test

,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,conn_state,local_orig,local_resp,missed_bytes,history,...,resp_ip_bytes,icmp,tcp,udp,service_-,dhcp,dns,dtls,http,ssl
0,60389,445,-,-,-,SH,T,T,0,F,...,0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,52090,443,0.028626,0,0,SF,T,F,0,FafA,...,80,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,59672,443,0.028758,0,0,SF,T,F,0,FafA,...,80,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,57505,443,0.028336,0,0,SF,T,F,0,FafA,...,80,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,52090,443,0.028459,0,0,SF,T,F,0,FafA,...,80,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1626,137,137,17.497227,900,0,S0,T,T,0,D,...,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1627,138,138,-,-,-,S0,T,T,0,D,...,0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1628,33561,445,-,-,-,SH,T,T,0,F,...,0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1629,50410,443,20.098036,1647,1064,SF,T,F,0,ShADadfF,...,1668,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1630,50410,443,20.098292,1647,1064,SF,T,F,0,ShADadfF,...,1668,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [30]:
# 6. duration 전처리 - '-' 데이터 0으로 변경 후 float형으로 변경, 스케일링

test['duration'] = test['duration'].str.replace('-', '0')
test['duration'] = test['duration'].astype('float64')
scaler = StandardScaler()
test['duration'] = scaler.fit_transform(test[['duration']])
test

,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,conn_state,local_orig,local_resp,missed_bytes,history,...,resp_ip_bytes,icmp,tcp,udp,service_-,dhcp,dns,dtls,http,ssl
0,60389,445,-0.358348,-,-,SH,T,T,0,F,...,0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,52090,443,-0.357988,0,0,SF,T,F,0,FafA,...,80,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,59672,443,-0.357987,0,0,SF,T,F,0,FafA,...,80,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,57505,443,-0.357992,0,0,SF,T,F,0,FafA,...,80,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,52090,443,-0.357990,0,0,SF,T,F,0,FafA,...,80,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1626,137,137,-0.138590,900,0,S0,T,T,0,D,...,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1627,138,138,-0.358348,-,-,S0,T,T,0,D,...,0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1628,33561,445,-0.358348,-,-,SH,T,T,0,F,...,0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1629,50410,443,-0.105925,1647,1064,SF,T,F,0,ShADadfF,...,1668,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1630,50410,443,-0.105922,1647,1064,SF,T,F,0,ShADadfF,...,1668,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [31]:
# 7. orig_bytes, resp_bytes 전처리 - '-' 데이터 0으로 변경 후 float형으로 변경, 스케일링

test['orig_bytes'] = test['orig_bytes'].str.replace('-', '0')
test['orig_bytes'] = test['orig_bytes'].astype('float64')
scaler = StandardScaler()
test['orig_bytes'] = scaler.fit_transform(test[['orig_bytes']])

test['resp_bytes'] = test['resp_bytes'].str.replace('-', '0')
test['resp_bytes'] = test['resp_bytes'].astype('float64')
scaler = StandardScaler()
test['resp_bytes'] = scaler.fit_transform(test[['resp_bytes']])

test

,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,conn_state,local_orig,local_resp,missed_bytes,history,...,resp_ip_bytes,icmp,tcp,udp,service_-,dhcp,dns,dtls,http,ssl
0,60389,445,-0.358348,-0.170351,-0.109114,SH,T,T,0,F,...,0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,52090,443,-0.357988,-0.170351,-0.109114,SF,T,F,0,FafA,...,80,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,59672,443,-0.357987,-0.170351,-0.109114,SF,T,F,0,FafA,...,80,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,57505,443,-0.357992,-0.170351,-0.109114,SF,T,F,0,FafA,...,80,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,52090,443,-0.357990,-0.170351,-0.109114,SF,T,F,0,FafA,...,80,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1626,137,137,-0.138590,-0.126223,-0.109114,S0,T,T,0,D,...,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1627,138,138,-0.358348,-0.170351,-0.109114,S0,T,T,0,D,...,0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1628,33561,445,-0.358348,-0.170351,-0.109114,SH,T,T,0,F,...,0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1629,50410,443,-0.105925,-0.089597,-0.108217,SF,T,F,0,ShADadfF,...,1668,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1630,50410,443,-0.105922,-0.089597,-0.108217,SF,T,F,0,ShADadfF,...,1668,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [32]:
# conn_state 전처리 - one-hot encoding

conn_state_ohe_df = pd.DataFrame(conn_state_ohe.transform(test[['conn_state']]), columns=conn_state_ohe.categories_[0], index=test.index)
test = pd.concat([test, conn_state_ohe_df], axis=1)
test.drop(['conn_state'], axis=1, inplace=True)
test

,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,local_orig,local_resp,missed_bytes,history,orig_pkts,...,RSTO,RSTR,RSTRH,S0,S1,S2,S3,SF,SH,SHR
0,60389,445,-0.358348,-0.170351,-0.109114,T,T,0,F,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,52090,443,-0.357988,-0.170351,-0.109114,T,F,0,FafA,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,59672,443,-0.357987,-0.170351,-0.109114,T,F,0,FafA,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,57505,443,-0.357992,-0.170351,-0.109114,T,F,0,FafA,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,52090,443,-0.357990,-0.170351,-0.109114,T,F,0,FafA,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1626,137,137,-0.138590,-0.126223,-0.109114,T,T,0,D,18,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1627,138,138,-0.358348,-0.170351,-0.109114,T,T,0,D,1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1628,33561,445,-0.358348,-0.170351,-0.109114,T,T,0,F,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1629,50410,443,-0.105925,-0.089597,-0.108217,T,F,0,ShADadfF,13,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1630,50410,443,-0.105922,-0.089597,-0.108217,T,F,0,ShADadfF,13,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [33]:
# local_orig, local_resp 전처리 - one-hot encoding

local_orig_ohe_df = pd.DataFrame(local_orig_ohe.transform(test[['local_orig']]), columns=['local_orig_F', 'local_orig_T'], index=test.index)
test = pd.concat([test, local_orig_ohe_df], axis=1)
test.drop(['local_orig'], axis=1, inplace=True)

local_resp_ohe_df = pd.DataFrame(local_resp_ohe.transform(test[['local_resp']]), columns=['local_resp_F', 'local_resp_T'], index=test.index)
test = pd.concat([test, local_resp_ohe_df], axis=1)
test.drop(['local_resp'], axis=1, inplace=True)

test

,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,...,S1,S2,S3,SF,SH,SHR,local_orig_F,local_orig_T,local_resp_F,local_resp_T
0,60389,445,-0.358348,-0.170351,-0.109114,0,F,1,52,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
1,52090,443,-0.357988,-0.170351,-0.109114,0,FafA,2,80,2,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
2,59672,443,-0.357987,-0.170351,-0.109114,0,FafA,2,80,2,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
3,57505,443,-0.357992,-0.170351,-0.109114,0,FafA,2,80,2,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
4,52090,443,-0.357990,-0.170351,-0.109114,0,FafA,2,80,2,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1626,137,137,-0.138590,-0.126223,-0.109114,0,D,18,1404,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1627,138,138,-0.358348,-0.170351,-0.109114,0,D,1,229,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1628,33561,445,-0.358348,-0.170351,-0.109114,0,F,1,52,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
1629,50410,443,-0.105925,-0.089597,-0.108217,0,ShADadfF,13,2179,15,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
1630,50410,443,-0.105922,-0.089597,-0.108217,0,ShADadfF,13,2179,15,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0

In [34]:
# missed_bytes 전처리 - 스케일링

scaler = StandardScaler()
test['missed_bytes'] = scaler.fit_transform(test[['missed_bytes']])
test

,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,...,S1,S2,S3,SF,SH,SHR,local_orig_F,local_orig_T,local_resp_F,local_resp_T
0,60389,445,-0.358348,-0.170351,-0.109114,-0.090456,F,1,52,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
1,52090,443,-0.357988,-0.170351,-0.109114,-0.090456,FafA,2,80,2,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
2,59672,443,-0.357987,-0.170351,-0.109114,-0.090456,FafA,2,80,2,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
3,57505,443,-0.357992,-0.170351,-0.109114,-0.090456,FafA,2,80,2,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
4,52090,443,-0.357990,-0.170351,-0.109114,-0.090456,FafA,2,80,2,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1626,137,137,-0.138590,-0.126223,-0.109114,-0.090456,D,18,1404,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1627,138,138,-0.358348,-0.170351,-0.109114,-0.090456,D,1,229,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1628,33561,445,-0.358348,-0.170351,-0.109114,-0.090456,F,1,52,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
1629,50410,443,-0.105925,-0.089597,-0.108217,-0.090456,ShADadfF,13,2179,15,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
1630,50410,443,-0.105922,-0.089597,-0.108217,-0.090456,ShADadfF,13,2179,15,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0

In [35]:
# history 전처리 - one-hot encoding, 만약 train 데이터에 없는 데이터가 있을 경우 0으로 채워줌

try:
    history_ohe_df = pd.DataFrame(history_ohe.transform(test[['history']]), columns=history_ohe.categories_[0], index=test.index)
except:
    history_ohe_df = pd.DataFrame(np.zeros((len(test), len(history_ohe.categories_[0]))), columns=history_ohe.categories_[0], index=test.index)
    
test = pd.concat([test, history_ohe_df], axis=1)
test.drop(['history'], axis=1, inplace=True)
test

,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,...,ShfqR,^d,^dCa,^dCaf,^hCacdfA,^hCacdfR,^hCadc,^hCadcfA,^hCadfA,^r
0,60389,445,-0.358348,-0.170351,-0.109114,-0.090456,1,52,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,52090,443,-0.357988,-0.170351,-0.109114,-0.090456,2,80,2,80,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,59672,443,-0.357987,-0.170351,-0.109114,-0.090456,2,80,2,80,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,57505,443,-0.357992,-0.170351,-0.109114,-0.090456,2,80,2,80,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,52090,443,-0.357990,-0.170351,-0.109114,-0.090456,2,80,2,80,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1626,137,137,-0.138590,-0.126223,-0.109114,-0.090456,18,1404,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1627,138,138,-0.358348,-0.170351,-0.109114,-0.090456,1,229,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1628,33561,445,-0.358348,-0.170351,-0.109114,-0.090456,1,52,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1629,50410,443,-0.105925,-0.089597,-0.108217,-0.090456,13,2179,15,1668,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1630,50410,443,-0.105922,-0.089597,-0.108217,-0.090456,13,2179,15,1668,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:
# orig_pkts, orig_ip_bytes, resp_pkts, resp_ip_bytes 전처리 - 스케일링

scaler = StandardScaler()
test['orig_pkts'] = scaler.fit_transform(test[['orig_pkts']])
test['orig_ip_bytes'] = scaler.fit_transform(test[['orig_ip_bytes']])
test['resp_pkts'] = scaler.fit_transform(test[['resp_pkts']])
test['resp_ip_bytes'] = scaler.fit_transform(test[['resp_ip_bytes']])
test

,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,...,ShfqR,^d,^dCa,^dCaf,^hCacdfA,^hCacdfR,^hCadc,^hCadcfA,^hCadfA,^r
0,60389,445,-0.358348,-0.170351,-0.109114,-0.090456,-0.115393,-0.162864,-0.064189,-0.095173,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,52090,443,-0.357988,-0.170351,-0.109114,-0.090456,-0.111748,-0.161800,-0.062345,-0.095098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,59672,443,-0.357987,-0.170351,-0.109114,-0.090456,-0.111748,-0.161800,-0.062345,-0.095098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,57505,443,-0.357992,-0.170351,-0.109114,-0.090456,-0.111748,-0.161800,-0.062345,-0.095098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,52090,443,-0.357990,-0.170351,-0.109114,-0.090456,-0.111748,-0.161800,-0.062345,-0.095098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1626,137,137,-0.138590,-0.126223,-0.109114,-0.090456,-0.053416,-0.111489,-0.064189,-0.095173,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1627,138,138,-0.358348,-0.170351,-0.109114,-0.090456,-0.115393,-0.156138,-0.064189,-0.095173,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1628,33561,445,-0.358348,-0.170351,-0.109114,-0.090456,-0.115393,-0.162864,-0.064189,-0.095173,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1629,50410,443,-0.105925,-0.089597,-0.108217,-0.090456,-0.071645,-0.082039,-0.050362,-0.093612,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1630,50410,443,-0.105922,-0.089597,-0.108217,-0.090456,-0.071645,-0.082039,-0.050362,-0.093612,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
train.shape, test.shape

((19733, 161), (1631, 161))

In [38]:
# train 데이터셋과 test 데이터셋의 '-' 컬럼명을 'not'으로 변경

train.rename(columns={'-': 'not'}, inplace=True)
test.rename(columns={'-': 'not'}, inplace=True)

In [39]:
# 데이터 스플릿

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(train, train_label, test_size=0.2, random_state=42)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

((15786, 161), (3947, 161), (15786,), (3947,))

In [40]:
# 모델 학습

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
 
lr = LogisticRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)
accuracy_score(y_test, y_pred)

c:\Users\Gloomy\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.9989865720800608

In [41]:
# test 데이터 예측

y_pred = lr.predict(test)
accuracy_score(y_pred, answer['class'])

0.9950950337216432

In [42]:
# RandomForest

# from sklearn.ensemble import RandomForestClassifier

# rf = RandomForestClassifier()
# rf.fit(x_train, y_train)
# y_pred = rf.predict(test)
# accuracy_score(y_pred, answer['class'])

In [43]:
# XGBoost

# from xgboost import XGBClassifier

# xgb = XGBClassifier()
# xgb.fit(x_train, y_train)
# y_pred = xgb.predict(test)
# accuracy_score(y_pred, answer['class'])

In [44]:
# LightGBM

# from lightgbm import LGBMClassifier

# lgbm = LGBMClassifier()
# lgbm.fit(x_train, y_train)
# y_pred = lgbm.predict(test)
# accuracy_score(y_pred, answer['class'])

In [45]:
# CatBoost

# from catboost import CatBoostClassifier

# cat = CatBoostClassifier()
# cat.fit(x_train, y_train)
# y_pred = cat.predict(test)
# accuracy_score(y_pred, answer['class'])

In [46]:
# dense

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(128, activation='relu', input_dim=161))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:From c:\Users\Gloomy\anaconda3\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From c:\Users\Gloomy\anaconda3\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From c:\Users\Gloomy\anaconda3\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [47]:
# early stopping

from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(monitor='val_loss', patience=10)

# 모델 학습

model.fit(x_train.values, y_train.values, epochs=100, batch_size=32, validation_split=0.2, callbacks=[early_stopping])

Epoch 1/100
WARNING:tensorflow:From c:\Users\Gloomy\anaconda3\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\Gloomy\anaconda3\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

395/395 [==============================] - 2s 2ms/step - loss: 45.1784 - accuracy: 0.5290 - val_loss: 40.7686 - val_accuracy: 0.5811
Epoch 2/100
395/395 [==============================] - 1s 2ms/step - loss: 18.0565 - accuracy: 0.5500 - val_loss: 4.5811 - val_accuracy: 0.5503
Epoch 3/100
395/395 [==============================] - 1s 2ms/step - loss: 11.5670 - accuracy: 0.5820 - val_loss: 17.2064 - val_accuracy: 0.5782
Epoch 4/100
395/395 [==============================] - 1s 1ms/step - loss: 14.3887 - accuracy: 0.5691 - val_loss: 4.1562 - val_accuracy: 0.5785
Epoch 5/100
395/395 [==============================] - 1s 2ms/step - loss: 3.9196 - accuracy: 0.6902 - val_loss: 3.1633 - val_accuracy: 0.5272
Epoch 6/100
395/395 [==============================] - 1s 2ms/step - loss: 2.1885 - accuracy: 0.7901 - val_loss: 0.5221 - val_accuracy: 0.9639
Epoch 7/100
395/395 [==============================] - 1s 2ms/step - loss: 1.6513 - accuracy: 0.7647 - val_loss: 0.6165 - val_accuracy: 0.9747
Epoch 8/100
395/395 [==============================] - 1s 1ms/step - loss: 1.1120 - accuracy: 0.8337 - val_loss: 3.9098 - val_accuracy: 0.5611
Epoch 9/100
395/395 [==============================] - 1s 2ms/step - loss: 2.3350 - accuracy: 0.7998 - val_loss: 3.9642 - val_accuracy: 0.5665
Epoch 10/100
395/395 [==============================] - 1s 1ms/step - loss: 1.5231 - accuracy: 0.8036 - val_loss: 2.1611 - val_accuracy: 0.6143
Epoch 11/100
395/395 [==============================] - 1s 1ms/step - loss: 0.8902 - accuracy: 0.8703 - val_loss: 0.0816 - val_accuracy: 0.9962
Epoch 12/100
395/395 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.9145 - val_loss: 1.9425 - val_accuracy: 0.5858
Epoch 13/100
395/395 [==============================] - 1s 2ms/step - loss: 1.3478 - accuracy: 0.8266 - val_loss: 0.0804 - val_accuracy: 0.9858
Epoch 14/100
395/395 [==============================] - 1s 2ms/step - loss: 0.4313 - accuracy: 0.9294 - val_loss: 1.5930 - val_accuracy: 0.7201
Epoch 15/100
395/395 [==============================] - 1s 1ms/step - loss: 0.4310 - accuracy: 0.9390 - val_loss: 0.7579 - val_accuracy: 0.8762
Epoch 16/100
395/395 [==============================] - 1s 2ms/step - loss: 4.4789 - accuracy: 0.7773 - val_loss: 0.2638 - val_accuracy: 0.9649
Epoch 17/100
395/395 [==============================] - 1s 1ms/step - loss: 0.9904 - accuracy: 0.8872 - val_loss: 0.1382 - val_accuracy: 0.9772
Epoch 18/100
395/395 [==============================] - 1s 1ms/step - loss: 0.4056 - accuracy: 0.9217 - val_loss: 0.0587 - val_accuracy: 0.9949
Epoch 19/100
395/395 [==============================] - 1s 2ms/step - loss: 0.2796 - accuracy: 0.9687 - val_loss: 0.0508 - val_accuracy: 0.9763
Epoch 20/100
395/395 [==============================] - 1s 1ms/step - loss: 0.3209 - accuracy: 0.9409 - val_loss: 0.0183 - val_accuracy: 0.9972
Epoch 21/100
395/395 [==============================] - 1s 1ms/step - loss: 0.2319 - accuracy: 0.9571 - val_loss: 0.4859 - val_accuracy: 0.8930
Epoch 22/100
395/395 [==============================] - 1s 2ms/step - loss: 0.3457 - accuracy: 0.9478 - val_loss: 0.6702 - val_accuracy: 0.6783
Epoch 23/100
395/395 [==============================] - 1s 2ms/step - loss: 0.3597 - accuracy: 0.9222 - val_loss: 0.2688 - val_accuracy: 0.8955
Epoch 24/100
395/395 [==============================] - 1s 2ms/step - loss: 0.2117 - accuracy: 0.9519 - val_loss: 0.3489 - val_accuracy: 0.8955
Epoch 25/100
395/395 [==============================] - 1s 1ms/step - loss: 0.1057 - accuracy: 0.9719 - val_loss: 0.0307 - val_accuracy: 0.9778
Epoch 26/100
395/395 [==============================] - 1s 2ms/step - loss: 0.0709 - accuracy: 0.9814 - val_loss: 0.0411 - val_accuracy: 0.9959
Epoch 27/100
395/395 [==============================] - 1s 1ms/step - loss: 0.3021 - accuracy: 0.8973 - val_loss: 0.5201 - val_accuracy: 0.5940
Epoch 28/100
395/395 [==============================] - 1s 1ms/step - loss: 0.2764 - accuracy: 0.9108 - val_loss: 0.1550 - val_accuracy: 0.9826
Epoch 29/100
395/395 [==============================] - 1s 2ms/step - loss: 0.3466 - accuracy: 0.9190 - val_loss: 0.1695 - val_accuracy: 0.8733
Epoch 30/100
395/395 [==============================] - 1s 1ms/step - loss: 0.1271 - accuracy: 0.9567 - val_loss: 0.1068 - val_accuracy: 0.9820

In [48]:
y_pred = model.predict(test.values)
y_pred = np.where(y_pred > 0.5, 1, 0)
accuracy_score(y_pred, answer['class'])

51/51 [==============================] - 0s 781us/step

0.8663396689147762